// Builds /kz/ and /en/ copies of index.html from the Russian source.
// Runs at the end of build.mjs (after asset hashes are stamped); on its own: node scripts/build-i18n.mjs
// Fails when a Russian fragment from i18n/pages.mjs no longer exists in the source,
// and warns about Russian text left untranslated in the output.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import * as dict from '../i18n/pages.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const LANGS = {
  kk: {
    dir: 'kz', col: 1,
    // Manrope and Unbounded lack Kazakh letters, so Onest covers the text; Unbounded stays only for the Latin wordmark
    fonts: 'https://fonts.googleapis.com/css2?family=Onest:wght@400;500;600;700;800&family=Unbounded:wght@600&display=swap',
  },
  en: { dir: 'en', col: 2, fonts: null },
};

// Whitespace-insensitive search: formatting of the source HTML may change without breaking the dictionary
const toRegex = s => new RegExp(s.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/\s+/g, '\\s+'), 'g');

function translate(html, entries, col, file) {
  const missing = [];
  const slots = [];
  // Longest fragments first; matches become placeholders so a short fragment can't hit inside a replaced one
  const sorted = [...entries].sort((a, b) => b[0].length - a[0].length);
  for (const e of sorted) {
    let hit = false;
    html = html.replace(toRegex(e[0]), () => { hit = true; slots.push(e[col]); return '\u0000' + (slots.length - 1) + '\u0000'; });
    if (!hit) missing.push(e[0]);
  }
  if (missing.length) {
    console.error(`\n✖ ${file}: ${missing.length} fragment(s) from i18n/pages.mjs not found in the Russian source:`);
    missing.forEach(m => console.error('   • ' + m.slice(0, 110)));
    process.exitCode = 1;
  }
  return html.replace(/\u0000(\d+)\u0000/g, (_, i) => slots[+i]);
}

// Pages live one folder deeper, so relative asset URLs get a ../ prefix
const SKIP = /^(#|\/|[a-z]+:)/i;
const rebase = html => html.replace(/\b(src|href)="([^"]*)"/g, (m, attr, url) => SKIP.test(url) || !url ? m : `${attr}="../${url}"`);

const hash = f => createHash('sha256').update(readFileSync(join(ROOT, f))).digest('hex').slice(0, 10);

function localize(html, lang) {
  const L = LANGS[lang];
  // Source comments are Russian dev notes; the copy gets a single "generated" marker instead
  html = html.replace(/<!--[\s\S]*?-->\n?/g, '');
  html = html.replace('<html lang="ru">', `<!-- Generated by scripts/build-i18n.mjs from /index.html — edit the Russian source and i18n/, then run node build.mjs -->\n<html lang="${lang}">`);
  if (L.fonts) html = html.replace(/<link href="https:\/\/fonts\.googleapis\.com\/css2\?[^"]*" rel="stylesheet">/, `<link href="${L.fonts}" rel="stylesheet">`);
  // The switcher marks the current language
  html = html.replace(/(data-lang="ru") aria-current="page"/g, '$1');
  html = html.replace(new RegExp(`(data-lang="${lang}")`, 'g'), '$1 aria-current="page"');
  html = rebase(html);
  // Strings for brief.js load first; both scripts are deferred, so order is kept
  const f = `i18n/${lang}.js`;
  html = html.replace(/<script src="\.\.\/assets\/brief\.js\?v=[\w-]+" defer><\/script>/,
    m => `<script src="../${f}?v=${hash(f)}" defer></script>\n${m}`);
  if (!html.includes(`../${f}?v=`)) { console.error(`✖ ${lang}: brief.js script tag not found`); process.exitCode = 1; }
  return html;
}

// Text that legitimately stays the same in the translated page
const KEEP = new Set(['Altyn Click', 'Instagram / 2ГИС', 'Рус', 'Қаз', 'Eng', 'Instagram', 'TikTok', 'WhatsApp', 'Telegram', 'Email', 'Altegio', 'YCLIENTS', 'Онлайн', 'Бизнес', 'Сайт', 'Алматы', 'Астана', 'Шымкент', 'Логотип', 'Лицензия', 'Менеджер', 'Бюджет', 'Авто', 'Фитнес / спорт', 'Стоматология / клиника', 'Прайс / презентация', 'Брендбук / гайдлайн', 'Логотип, фото, прайс', 'Бриф — Altyn Click']);
const visible = html => {
  const body = html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<svg[\s\S]*?<\/svg>/g, '');
  const text = [...body.matchAll(/>([^<>]+)</g)].map(m => m[1]);
  const attrs = [...body.matchAll(/\b(?:placeholder|title|aria-label|data-other|content)="([^"]*)"/g)].map(m => m[1]);
  return [...text, ...attrs].map(t => t.replace(/\s+/g, ' ').trim()).filter(t => /[А-Яа-яЁё]{3}/.test(t) && !KEEP.has(t));
};

function check(src, out, lang) {
  const left = new Set(visible(out));
  const same = [...new Set(visible(src))].filter(t => left.has(t));
  if (same.length) {
    console.warn(`⚠ ${lang}: untranslated text:`);
    same.forEach(t => console.warn('   • ' + t.slice(0, 110)));
  }
  if (lang === 'en') {
    const cyr = visible(out).filter(t => !['Рус', 'Қаз'].includes(t));
    if (cyr.length) { console.warn('⚠ en: Cyrillic left:'); cyr.forEach(t => console.warn('   • ' + t.slice(0, 110))); }
  }
}

const src = readFileSync(join(ROOT, 'index.html'), 'utf8');
for (const [lang, L] of Object.entries(LANGS)) {
  const out = localize(translate(src, dict.index, L.col, lang), lang);
  check(src, out, lang);
  const dest = join(ROOT, L.dir, 'index.html');
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, out);
  console.log(`✓ ${L.dir}/index.html`);
}
